// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/image.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sensor/image.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto_messages {

namespace {

const ::google::protobuf::Descriptor* OpencvImage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OpencvImage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_sensor_2fimage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_sensor_2fimage_2eproto() {
  protobuf_AddDesc_sensor_2fimage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sensor/image.proto");
  GOOGLE_CHECK(file != NULL);
  OpencvImage_descriptor_ = file->message_type(0);
  static const int OpencvImage_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpencvImage, rows_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpencvImage, cols_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpencvImage, elt_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpencvImage, mat_data_),
  };
  OpencvImage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      OpencvImage_descriptor_,
      OpencvImage::default_instance_,
      OpencvImage_offsets_,
      -1,
      -1,
      -1,
      sizeof(OpencvImage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpencvImage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpencvImage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sensor_2fimage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      OpencvImage_descriptor_, &OpencvImage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sensor_2fimage_2eproto() {
  delete OpencvImage::default_instance_;
  delete OpencvImage_reflection_;
}

void protobuf_AddDesc_sensor_2fimage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_sensor_2fimage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022sensor/image.proto\022\016proto_messages\"M\n\013"
    "OpencvImage\022\014\n\004rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005\022"
    "\020\n\010elt_type\030\003 \001(\005\022\020\n\010mat_data\030\004 \001(\014b\006pro"
    "to3", 123);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sensor/image.proto", &protobuf_RegisterTypes);
  OpencvImage::default_instance_ = new OpencvImage();
  OpencvImage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sensor_2fimage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sensor_2fimage_2eproto {
  StaticDescriptorInitializer_sensor_2fimage_2eproto() {
    protobuf_AddDesc_sensor_2fimage_2eproto();
  }
} static_descriptor_initializer_sensor_2fimage_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OpencvImage::kRowsFieldNumber;
const int OpencvImage::kColsFieldNumber;
const int OpencvImage::kEltTypeFieldNumber;
const int OpencvImage::kMatDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OpencvImage::OpencvImage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto_messages.OpencvImage)
}

void OpencvImage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

OpencvImage::OpencvImage(const OpencvImage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:proto_messages.OpencvImage)
}

void OpencvImage::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  rows_ = 0;
  cols_ = 0;
  elt_type_ = 0;
  mat_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

OpencvImage::~OpencvImage() {
  // @@protoc_insertion_point(destructor:proto_messages.OpencvImage)
  SharedDtor();
}

void OpencvImage::SharedDtor() {
  mat_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void OpencvImage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OpencvImage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OpencvImage_descriptor_;
}

const OpencvImage& OpencvImage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sensor_2fimage_2eproto();
  return *default_instance_;
}

OpencvImage* OpencvImage::default_instance_ = NULL;

OpencvImage* OpencvImage::New(::google::protobuf::Arena* arena) const {
  OpencvImage* n = new OpencvImage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OpencvImage::Clear() {
// @@protoc_insertion_point(message_clear_start:proto_messages.OpencvImage)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(OpencvImage, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<OpencvImage*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(rows_, cols_);
  elt_type_ = 0;
  mat_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool OpencvImage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto_messages.OpencvImage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 rows = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rows_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_cols;
        break;
      }

      // optional int32 cols = 2;
      case 2: {
        if (tag == 16) {
         parse_cols:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cols_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_elt_type;
        break;
      }

      // optional int32 elt_type = 3;
      case 3: {
        if (tag == 24) {
         parse_elt_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &elt_type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_mat_data;
        break;
      }

      // optional bytes mat_data = 4;
      case 4: {
        if (tag == 34) {
         parse_mat_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_mat_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto_messages.OpencvImage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto_messages.OpencvImage)
  return false;
#undef DO_
}

void OpencvImage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto_messages.OpencvImage)
  // optional int32 rows = 1;
  if (this->rows() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->rows(), output);
  }

  // optional int32 cols = 2;
  if (this->cols() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->cols(), output);
  }

  // optional int32 elt_type = 3;
  if (this->elt_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->elt_type(), output);
  }

  // optional bytes mat_data = 4;
  if (this->mat_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->mat_data(), output);
  }

  // @@protoc_insertion_point(serialize_end:proto_messages.OpencvImage)
}

::google::protobuf::uint8* OpencvImage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto_messages.OpencvImage)
  // optional int32 rows = 1;
  if (this->rows() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->rows(), target);
  }

  // optional int32 cols = 2;
  if (this->cols() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->cols(), target);
  }

  // optional int32 elt_type = 3;
  if (this->elt_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->elt_type(), target);
  }

  // optional bytes mat_data = 4;
  if (this->mat_data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->mat_data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:proto_messages.OpencvImage)
  return target;
}

int OpencvImage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:proto_messages.OpencvImage)
  int total_size = 0;

  // optional int32 rows = 1;
  if (this->rows() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rows());
  }

  // optional int32 cols = 2;
  if (this->cols() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cols());
  }

  // optional int32 elt_type = 3;
  if (this->elt_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->elt_type());
  }

  // optional bytes mat_data = 4;
  if (this->mat_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->mat_data());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OpencvImage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto_messages.OpencvImage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const OpencvImage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const OpencvImage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto_messages.OpencvImage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto_messages.OpencvImage)
    MergeFrom(*source);
  }
}

void OpencvImage::MergeFrom(const OpencvImage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto_messages.OpencvImage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.rows() != 0) {
    set_rows(from.rows());
  }
  if (from.cols() != 0) {
    set_cols(from.cols());
  }
  if (from.elt_type() != 0) {
    set_elt_type(from.elt_type());
  }
  if (from.mat_data().size() > 0) {

    mat_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mat_data_);
  }
}

void OpencvImage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto_messages.OpencvImage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OpencvImage::CopyFrom(const OpencvImage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto_messages.OpencvImage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OpencvImage::IsInitialized() const {

  return true;
}

void OpencvImage::Swap(OpencvImage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OpencvImage::InternalSwap(OpencvImage* other) {
  std::swap(rows_, other->rows_);
  std::swap(cols_, other->cols_);
  std::swap(elt_type_, other->elt_type_);
  mat_data_.Swap(&other->mat_data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OpencvImage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OpencvImage_descriptor_;
  metadata.reflection = OpencvImage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OpencvImage

// optional int32 rows = 1;
void OpencvImage::clear_rows() {
  rows_ = 0;
}
 ::google::protobuf::int32 OpencvImage::rows() const {
  // @@protoc_insertion_point(field_get:proto_messages.OpencvImage.rows)
  return rows_;
}
 void OpencvImage::set_rows(::google::protobuf::int32 value) {
  
  rows_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.OpencvImage.rows)
}

// optional int32 cols = 2;
void OpencvImage::clear_cols() {
  cols_ = 0;
}
 ::google::protobuf::int32 OpencvImage::cols() const {
  // @@protoc_insertion_point(field_get:proto_messages.OpencvImage.cols)
  return cols_;
}
 void OpencvImage::set_cols(::google::protobuf::int32 value) {
  
  cols_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.OpencvImage.cols)
}

// optional int32 elt_type = 3;
void OpencvImage::clear_elt_type() {
  elt_type_ = 0;
}
 ::google::protobuf::int32 OpencvImage::elt_type() const {
  // @@protoc_insertion_point(field_get:proto_messages.OpencvImage.elt_type)
  return elt_type_;
}
 void OpencvImage::set_elt_type(::google::protobuf::int32 value) {
  
  elt_type_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.OpencvImage.elt_type)
}

// optional bytes mat_data = 4;
void OpencvImage::clear_mat_data() {
  mat_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& OpencvImage::mat_data() const {
  // @@protoc_insertion_point(field_get:proto_messages.OpencvImage.mat_data)
  return mat_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void OpencvImage::set_mat_data(const ::std::string& value) {
  
  mat_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_messages.OpencvImage.mat_data)
}
 void OpencvImage::set_mat_data(const char* value) {
  
  mat_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_messages.OpencvImage.mat_data)
}
 void OpencvImage::set_mat_data(const void* value, size_t size) {
  
  mat_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_messages.OpencvImage.mat_data)
}
 ::std::string* OpencvImage::mutable_mat_data() {
  
  // @@protoc_insertion_point(field_mutable:proto_messages.OpencvImage.mat_data)
  return mat_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* OpencvImage::release_mat_data() {
  // @@protoc_insertion_point(field_release:proto_messages.OpencvImage.mat_data)
  
  return mat_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void OpencvImage::set_allocated_mat_data(::std::string* mat_data) {
  if (mat_data != NULL) {
    
  } else {
    
  }
  mat_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mat_data);
  // @@protoc_insertion_point(field_set_allocated:proto_messages.OpencvImage.mat_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_messages

// @@protoc_insertion_point(global_scope)
